name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
    sdk: ">=3.6.0 <3.7.0"

# Add regular dependencies here.
dependencies:
    bcrypt: ^1.1.3
    dart_jsonwebtoken: ^3.2.0
    postgres: ^3.5.6
    shelf: ^1.4.2
    shelf_cors_headers: ^0.1.5
    shelf_router: ^1.1.4
    # path: ^1.8.0
    http_parser: ^4.0.0
    mime: ^1.0.4
    shelf_multipart: ^1.0.0

dev_dependencies:
    lints: ^5.0.0
    test: ^1.24.0
